# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryRequestBO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryRequestBO.proto',
  package='com.purefun.fstp.core.bo',
  syntax='proto2',
  serialized_pb=_b('\n\x14QueryRequestBO.proto\x12\x18\x63om.purefun.fstp.core.bo\"\xa0\x01\n\x0eQueryRequestBO\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62oid\x18\x02 \x01(\x12\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x1a\n\x12requestServiceName\x18\x04 \x01(\t\x12\x1a\n\x12respondServiceName\x18\x05 \x01(\t\x12\x12\n\nquerytopic\x18\x06 \x01(\t\x12\x11\n\ttempTopic\x18\x07 \x01(\t')
)




_QUERYREQUESTBO = _descriptor.Descriptor(
  name='QueryRequestBO',
  full_name='com.purefun.fstp.core.bo.QueryRequestBO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='com.purefun.fstp.core.bo.QueryRequestBO.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boid', full_name='com.purefun.fstp.core.bo.QueryRequestBO.boid', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.purefun.fstp.core.bo.QueryRequestBO.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestServiceName', full_name='com.purefun.fstp.core.bo.QueryRequestBO.requestServiceName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='respondServiceName', full_name='com.purefun.fstp.core.bo.QueryRequestBO.respondServiceName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='querytopic', full_name='com.purefun.fstp.core.bo.QueryRequestBO.querytopic', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tempTopic', full_name='com.purefun.fstp.core.bo.QueryRequestBO.tempTopic', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['QueryRequestBO'] = _QUERYREQUESTBO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequestBO = _reflection.GeneratedProtocolMessageType('QueryRequestBO', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUESTBO,
  __module__ = 'QueryRequestBO_pb2'
  # @@protoc_insertion_point(class_scope:com.purefun.fstp.core.bo.QueryRequestBO)
  ))
_sym_db.RegisterMessage(QueryRequestBO)


# @@protoc_insertion_point(module_scope)
