# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestBO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TestBO.proto',
  package='com.purefun.fstp.core.bo',
  syntax='proto2',
  serialized_pb=_b('\n\x0cTestBO.proto\x12\x18\x63om.purefun.fstp.core.bo\"Z\n\x06TestBO\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62oid\x18\x02 \x01(\x12\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x12\n\nservername\x18\x04 \x01(\t\x12\x0b\n\x03msg\x18\x05 \x01(\t')
)




_TESTBO = _descriptor.Descriptor(
  name='TestBO',
  full_name='com.purefun.fstp.core.bo.TestBO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='com.purefun.fstp.core.bo.TestBO.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boid', full_name='com.purefun.fstp.core.bo.TestBO.boid', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.purefun.fstp.core.bo.TestBO.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servername', full_name='com.purefun.fstp.core.bo.TestBO.servername', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.purefun.fstp.core.bo.TestBO.msg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['TestBO'] = _TESTBO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestBO = _reflection.GeneratedProtocolMessageType('TestBO', (_message.Message,), dict(
  DESCRIPTOR = _TESTBO,
  __module__ = 'TestBO_pb2'
  # @@protoc_insertion_point(class_scope:com.purefun.fstp.core.bo.TestBO)
  ))
_sym_db.RegisterMessage(TestBO)


# @@protoc_insertion_point(module_scope)
