# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExampleBO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExampleBO.proto',
  package='com.purefun.fstp.example.bo',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x45xampleBO.proto\x12\x1b\x63om.purefun.fstp.example.bo\"W\n\tExampleBO\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62oid\x18\x02 \x01(\x12\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05')
)




_EXAMPLEBO = _descriptor.Descriptor(
  name='ExampleBO',
  full_name='com.purefun.fstp.example.bo.ExampleBO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='com.purefun.fstp.example.bo.ExampleBO.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boid', full_name='com.purefun.fstp.example.bo.ExampleBO.boid', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.purefun.fstp.example.bo.ExampleBO.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.purefun.fstp.example.bo.ExampleBO.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.purefun.fstp.example.bo.ExampleBO.age', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['ExampleBO'] = _EXAMPLEBO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleBO = _reflection.GeneratedProtocolMessageType('ExampleBO', (_message.Message,), dict(
  DESCRIPTOR = _EXAMPLEBO,
  __module__ = 'ExampleBO_pb2'
  # @@protoc_insertion_point(class_scope:com.purefun.fstp.example.bo.ExampleBO)
  ))
_sym_db.RegisterMessage(ExampleBO)


# @@protoc_insertion_point(module_scope)
