// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryRequestBO.proto

package com.purefun.fstp.core.bo.pro;

public final class QueryRequestBO_PRO {
  private QueryRequestBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryRequestBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryRequestBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional sint64 boid = 2;</code>
     */
    boolean hasBoid();
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    long getBoid();

    /**
     * <code>optional string destination = 3;</code>
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    java.lang.String getDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    boolean hasRequestServiceName();
    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    java.lang.String getRequestServiceName();
    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestServiceNameBytes();

    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    boolean hasRespondServiceName();
    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    java.lang.String getRespondServiceName();
    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    com.google.protobuf.ByteString
        getRespondServiceNameBytes();

    /**
     * <code>optional string querytopic = 6;</code>
     */
    boolean hasQuerytopic();
    /**
     * <code>optional string querytopic = 6;</code>
     */
    java.lang.String getQuerytopic();
    /**
     * <code>optional string querytopic = 6;</code>
     */
    com.google.protobuf.ByteString
        getQuerytopicBytes();

    /**
     * <code>optional string tempTopic = 7;</code>
     */
    boolean hasTempTopic();
    /**
     * <code>optional string tempTopic = 7;</code>
     */
    java.lang.String getTempTopic();
    /**
     * <code>optional string tempTopic = 7;</code>
     */
    com.google.protobuf.ByteString
        getTempTopicBytes();
  }
  /**
   * Protobuf type {@code QueryRequestBO}
   */
  public  static final class QueryRequestBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryRequestBO)
      QueryRequestBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryRequestBO.newBuilder() to construct.
    private QueryRequestBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryRequestBO() {
      uuid_ = "";
      boid_ = 0L;
      destination_ = "";
      requestServiceName_ = "";
      respondServiceName_ = "";
      querytopic_ = "";
      tempTopic_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryRequestBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boid_ = input.readSInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destination_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              requestServiceName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              respondServiceName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              querytopic_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              tempTopic_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.internal_static_QueryRequestBO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.internal_static_QueryRequestBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.class, com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public boolean hasBoid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public long getBoid() {
      return boid_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <code>optional string destination = 3;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSERVICENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object requestServiceName_;
    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    public boolean hasRequestServiceName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    public java.lang.String getRequestServiceName() {
      java.lang.Object ref = requestServiceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestServiceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestServiceName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestServiceNameBytes() {
      java.lang.Object ref = requestServiceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestServiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONDSERVICENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object respondServiceName_;
    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    public boolean hasRespondServiceName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    public java.lang.String getRespondServiceName() {
      java.lang.Object ref = respondServiceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          respondServiceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string respondServiceName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRespondServiceNameBytes() {
      java.lang.Object ref = respondServiceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respondServiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERYTOPIC_FIELD_NUMBER = 6;
    private volatile java.lang.Object querytopic_;
    /**
     * <code>optional string querytopic = 6;</code>
     */
    public boolean hasQuerytopic() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string querytopic = 6;</code>
     */
    public java.lang.String getQuerytopic() {
      java.lang.Object ref = querytopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          querytopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string querytopic = 6;</code>
     */
    public com.google.protobuf.ByteString
        getQuerytopicBytes() {
      java.lang.Object ref = querytopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        querytopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPTOPIC_FIELD_NUMBER = 7;
    private volatile java.lang.Object tempTopic_;
    /**
     * <code>optional string tempTopic = 7;</code>
     */
    public boolean hasTempTopic() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string tempTopic = 7;</code>
     */
    public java.lang.String getTempTopic() {
      java.lang.Object ref = tempTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tempTopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tempTopic = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTempTopicBytes() {
      java.lang.Object ref = tempTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tempTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestServiceName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, respondServiceName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, querytopic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tempTopic_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestServiceName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, respondServiceName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, querytopic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tempTopic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO)) {
        return super.equals(obj);
      }
      com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO other = (com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasBoid() == other.hasBoid());
      if (hasBoid()) {
        result = result && (getBoid()
            == other.getBoid());
      }
      result = result && (hasDestination() == other.hasDestination());
      if (hasDestination()) {
        result = result && getDestination()
            .equals(other.getDestination());
      }
      result = result && (hasRequestServiceName() == other.hasRequestServiceName());
      if (hasRequestServiceName()) {
        result = result && getRequestServiceName()
            .equals(other.getRequestServiceName());
      }
      result = result && (hasRespondServiceName() == other.hasRespondServiceName());
      if (hasRespondServiceName()) {
        result = result && getRespondServiceName()
            .equals(other.getRespondServiceName());
      }
      result = result && (hasQuerytopic() == other.hasQuerytopic());
      if (hasQuerytopic()) {
        result = result && getQuerytopic()
            .equals(other.getQuerytopic());
      }
      result = result && (hasTempTopic() == other.hasTempTopic());
      if (hasTempTopic()) {
        result = result && getTempTopic()
            .equals(other.getTempTopic());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasBoid()) {
        hash = (37 * hash) + BOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBoid());
      }
      if (hasDestination()) {
        hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
        hash = (53 * hash) + getDestination().hashCode();
      }
      if (hasRequestServiceName()) {
        hash = (37 * hash) + REQUESTSERVICENAME_FIELD_NUMBER;
        hash = (53 * hash) + getRequestServiceName().hashCode();
      }
      if (hasRespondServiceName()) {
        hash = (37 * hash) + RESPONDSERVICENAME_FIELD_NUMBER;
        hash = (53 * hash) + getRespondServiceName().hashCode();
      }
      if (hasQuerytopic()) {
        hash = (37 * hash) + QUERYTOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getQuerytopic().hashCode();
      }
      if (hasTempTopic()) {
        hash = (37 * hash) + TEMPTOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTempTopic().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryRequestBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryRequestBO)
        com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.internal_static_QueryRequestBO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.internal_static_QueryRequestBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.class, com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.Builder.class);
      }

      // Construct using com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        boid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        requestServiceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        respondServiceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        querytopic_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        tempTopic_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.internal_static_QueryRequestBO_descriptor;
      }

      public com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO getDefaultInstanceForType() {
        return com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.getDefaultInstance();
      }

      public com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO build() {
        com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO buildPartial() {
        com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO result = new com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.boid_ = boid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestServiceName_ = requestServiceName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.respondServiceName_ = respondServiceName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.querytopic_ = querytopic_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.tempTopic_ = tempTopic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO) {
          return mergeFrom((com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO other) {
        if (other == com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasBoid()) {
          setBoid(other.getBoid());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00000004;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasRequestServiceName()) {
          bitField0_ |= 0x00000008;
          requestServiceName_ = other.requestServiceName_;
          onChanged();
        }
        if (other.hasRespondServiceName()) {
          bitField0_ |= 0x00000010;
          respondServiceName_ = other.respondServiceName_;
          onChanged();
        }
        if (other.hasQuerytopic()) {
          bitField0_ |= 0x00000020;
          querytopic_ = other.querytopic_;
          onChanged();
        }
        if (other.hasTempTopic()) {
          bitField0_ |= 0x00000040;
          tempTopic_ = other.tempTopic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public boolean hasBoid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder setBoid(long value) {
        bitField0_ |= 0x00000002;
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder clearBoid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>optional string destination = 3;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destination_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestServiceName_ = "";
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public boolean hasRequestServiceName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public java.lang.String getRequestServiceName() {
        java.lang.Object ref = requestServiceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestServiceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestServiceNameBytes() {
        java.lang.Object ref = requestServiceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestServiceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public Builder setRequestServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestServiceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public Builder clearRequestServiceName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestServiceName_ = getDefaultInstance().getRequestServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestServiceName = 4;</code>
       */
      public Builder setRequestServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestServiceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object respondServiceName_ = "";
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public boolean hasRespondServiceName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public java.lang.String getRespondServiceName() {
        java.lang.Object ref = respondServiceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            respondServiceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRespondServiceNameBytes() {
        java.lang.Object ref = respondServiceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respondServiceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public Builder setRespondServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        respondServiceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public Builder clearRespondServiceName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        respondServiceName_ = getDefaultInstance().getRespondServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string respondServiceName = 5;</code>
       */
      public Builder setRespondServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        respondServiceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object querytopic_ = "";
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public boolean hasQuerytopic() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public java.lang.String getQuerytopic() {
        java.lang.Object ref = querytopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            querytopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public com.google.protobuf.ByteString
          getQuerytopicBytes() {
        java.lang.Object ref = querytopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          querytopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public Builder setQuerytopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        querytopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public Builder clearQuerytopic() {
        bitField0_ = (bitField0_ & ~0x00000020);
        querytopic_ = getDefaultInstance().getQuerytopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string querytopic = 6;</code>
       */
      public Builder setQuerytopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        querytopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tempTopic_ = "";
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public boolean hasTempTopic() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public java.lang.String getTempTopic() {
        java.lang.Object ref = tempTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tempTopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTempTopicBytes() {
        java.lang.Object ref = tempTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tempTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public Builder setTempTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tempTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public Builder clearTempTopic() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tempTopic_ = getDefaultInstance().getTempTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tempTopic = 7;</code>
       */
      public Builder setTempTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tempTopic_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryRequestBO)
    }

    // @@protoc_insertion_point(class_scope:QueryRequestBO)
    private static final com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO();
    }

    public static com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QueryRequestBO>
        PARSER = new com.google.protobuf.AbstractParser<QueryRequestBO>() {
      public QueryRequestBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryRequestBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryRequestBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryRequestBO> getParserForType() {
      return PARSER;
    }

    public com.purefun.fstp.core.bo.pro.QueryRequestBO_PRO.QueryRequestBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequestBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryRequestBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024QueryRequestBO.proto\032\031google/protobuf/" +
      "any.proto\"\240\001\n\016QueryRequestBO\022\014\n\004uuid\030\001 \001" +
      "(\t\022\014\n\004boid\030\002 \001(\022\022\023\n\013destination\030\003 \001(\t\022\032\n" +
      "\022requestServiceName\030\004 \001(\t\022\032\n\022respondServ" +
      "iceName\030\005 \001(\t\022\022\n\nquerytopic\030\006 \001(\t\022\021\n\ttem" +
      "pTopic\030\007 \001(\tB2\n\034com.purefun.fstp.core.bo" +
      ".proB\022QueryRequestBO_PRO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_QueryRequestBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryRequestBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryRequestBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Destination", "RequestServiceName", "RespondServiceName", "Querytopic", "TempTopic", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
