# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SourceStockBO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SourceStockBO.proto',
  package='com.purefun.fstp.core.bo',
  syntax='proto2',
  serialized_pb=_b('\n\x13SourceStockBO.proto\x12\x18\x63om.purefun.fstp.core.bo\"\xdd\x05\n\rSourceStockBO\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62oid\x18\x02 \x01(\x12\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x0f\n\x07secu_id\x18\x04 \x01(\t\x12\x0c\n\x04isin\x18\x05 \x01(\t\x12\x1a\n\x12record_update_time\x18\x06 \x01(\t\x12\x19\n\x11secu_chinese_name\x18\x07 \x01(\t\x12\x19\n\x11secu_english_name\x18\x08 \x01(\t\x12\x14\n\x0csecu_base_id\x18\t \x01(\t\x12\x11\n\texch_type\x18\n \x01(\t\x12\x11\n\tsecu_type\x18\x0b \x01(\t\x12\x15\n\rsecu_sub_type\x18\x0c \x01(\t\x12\x10\n\x08\x63urrency\x18\r \x01(\t\x12\x16\n\x0e\x62ond_par_value\x18\x0e \x01(\x01\x12\x17\n\x0fnot_list_stkqty\x18\x0f \x01(\t\x12\x17\n\x0flast_trade_date\x18\x10 \x01(\t\x12\x11\n\tlist_date\x18\x11 \x01(\t\x12\x16\n\x0eproduct_set_id\x18\x12 \x01(\t\x12\x10\n\x08\x62uy_unit\x18\x13 \x01(\x05\x12\x11\n\tsell_unit\x18\x14 \x01(\x05\x12\x17\n\x0ftrade_low_limit\x18\x15 \x01(\x05\x12\x18\n\x10trade_high_limit\x18\x16 \x01(\x05\x12\x17\n\x0fpre_close_price\x18\x17 \x01(\x01\x12\x12\n\ntick_price\x18\x18 \x01(\x01\x12\x18\n\x10price_limit_type\x18\x19 \x01(\t\x12\x18\n\x10price_high_limit\x18\x1a \x01(\x01\x12\x17\n\x0fprice_low_limit\x18\x1b \x01(\x01\x12\x16\n\x0e\x65x_right_ratio\x18\x1c \x01(\x01\x12\x16\n\x0e\x64ividend_price\x18\x1d \x01(\x01\x12\x16\n\x0e\x66inancing_flag\x18\x1e \x01(\t\x12\x13\n\x0bmargin_flag\x18\x1f \x01(\t\x12\x13\n\x0bsecu_status\x18  \x01(\t\x12\x0c\n\x04memo\x18! \x01(\t')
)




_SOURCESTOCKBO = _descriptor.Descriptor(
  name='SourceStockBO',
  full_name='com.purefun.fstp.core.bo.SourceStockBO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='com.purefun.fstp.core.bo.SourceStockBO.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boid', full_name='com.purefun.fstp.core.bo.SourceStockBO.boid', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.purefun.fstp.core.bo.SourceStockBO.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_id', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isin', full_name='com.purefun.fstp.core.bo.SourceStockBO.isin', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_update_time', full_name='com.purefun.fstp.core.bo.SourceStockBO.record_update_time', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_chinese_name', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_chinese_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_english_name', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_english_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_base_id', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_base_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exch_type', full_name='com.purefun.fstp.core.bo.SourceStockBO.exch_type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_type', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_type', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_sub_type', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_sub_type', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='com.purefun.fstp.core.bo.SourceStockBO.currency', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bond_par_value', full_name='com.purefun.fstp.core.bo.SourceStockBO.bond_par_value', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_list_stkqty', full_name='com.purefun.fstp.core.bo.SourceStockBO.not_list_stkqty', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_trade_date', full_name='com.purefun.fstp.core.bo.SourceStockBO.last_trade_date', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_date', full_name='com.purefun.fstp.core.bo.SourceStockBO.list_date', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_set_id', full_name='com.purefun.fstp.core.bo.SourceStockBO.product_set_id', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buy_unit', full_name='com.purefun.fstp.core.bo.SourceStockBO.buy_unit', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sell_unit', full_name='com.purefun.fstp.core.bo.SourceStockBO.sell_unit', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_low_limit', full_name='com.purefun.fstp.core.bo.SourceStockBO.trade_low_limit', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_high_limit', full_name='com.purefun.fstp.core.bo.SourceStockBO.trade_high_limit', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_close_price', full_name='com.purefun.fstp.core.bo.SourceStockBO.pre_close_price', index=22,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick_price', full_name='com.purefun.fstp.core.bo.SourceStockBO.tick_price', index=23,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_limit_type', full_name='com.purefun.fstp.core.bo.SourceStockBO.price_limit_type', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_high_limit', full_name='com.purefun.fstp.core.bo.SourceStockBO.price_high_limit', index=25,
      number=26, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_low_limit', full_name='com.purefun.fstp.core.bo.SourceStockBO.price_low_limit', index=26,
      number=27, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ex_right_ratio', full_name='com.purefun.fstp.core.bo.SourceStockBO.ex_right_ratio', index=27,
      number=28, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dividend_price', full_name='com.purefun.fstp.core.bo.SourceStockBO.dividend_price', index=28,
      number=29, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='financing_flag', full_name='com.purefun.fstp.core.bo.SourceStockBO.financing_flag', index=29,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='margin_flag', full_name='com.purefun.fstp.core.bo.SourceStockBO.margin_flag', index=30,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secu_status', full_name='com.purefun.fstp.core.bo.SourceStockBO.secu_status', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='com.purefun.fstp.core.bo.SourceStockBO.memo', index=32,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=783,
)

DESCRIPTOR.message_types_by_name['SourceStockBO'] = _SOURCESTOCKBO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SourceStockBO = _reflection.GeneratedProtocolMessageType('SourceStockBO', (_message.Message,), dict(
  DESCRIPTOR = _SOURCESTOCKBO,
  __module__ = 'SourceStockBO_pb2'
  # @@protoc_insertion_point(class_scope:com.purefun.fstp.core.bo.SourceStockBO)
  ))
_sym_db.RegisterMessage(SourceStockBO)


# @@protoc_insertion_point(module_scope)
